# Generated by Django 6.0.2 on 2026-04-28 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
