# Generated by Django 6.0.2 on 2026-04-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
